language: cpp
os: linux
dist: trusty
sudo: required
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq --allow-unauthenticated g++-8 libgtest-dev cmake
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

before_script:
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - make
  - sudo make install
  - cd ../..

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - ./algorithms_test

